Repository JuiceMitApfelnDrin/CodinCod, pull requests merged in 2025-02, with the labels that each got.

#27 feat: fetch puzzle languages from piston instead of hardcoded
  libs/backend/src/plugins/decorators/piston.ts
  libs/backend/src/router.ts
  libs/backend/src/routes/execute/index.ts
  libs/backend/src/routes/puzzle/languages/index.ts
  libs/backend/src/routes/submission/index.ts
  libs/backend/src/types/fastify.d.ts
  libs/backend/src/utils/functions/findRuntimeInfo.ts
  libs/frontend/src/lib/config/api.ts
  libs/frontend/src/lib/features/game/components/codemirror.svelte
  libs/frontend/src/lib/features/puzzles/components/edit-puzzle-form.svelte
  libs/frontend/src/lib/features/puzzles/components/play-puzzle.svelte
  libs/frontend/src/lib/utils/fetch-supported-languages.ts
  libs/frontend/src/routes/api/supported-languages/+server.ts
  libs/frontend/src/routes/api/verify-token/+server.ts
  libs/frontend/svelte.config.js
  libs/types/src/core/common/config/backend-urls.ts
  libs/types/src/core/game/schema/options.schema.ts
  libs/types/src/core/piston/config/execution-params.ts
  libs/types/src/core/piston/config/piston-urls.ts
  libs/types/src/core/piston/schema/runtime.ts
  libs/types/src/core/puzzle/config/languages.ts
  libs/types/src/core/puzzle/schema/puzzle-language.ts
  libs/types/src/core/puzzle/schema/solution.schema.ts
  libs/types/src/core/submission/config/submission-params.ts
  libs/types/src/index.ts
Labels: bug

#34 fix: username in standings table
  libs/backend/src/config/schema.ts
  libs/backend/src/models/submission/submission.ts
  libs/backend/src/routes/login/index.ts
  libs/backend/src/routes/puzzle/index.ts
  libs/backend/src/routes/register/index.ts
  libs/backend/src/websocket/game/on-connection.ts
  libs/frontend/src/lib/features/game/standings/components/standings-table.svelte
  libs/frontend/src/routes/(authenticated)/multiplayer/[id]/+page.svelte
Labels: bug

#36 redirect when game room id is present in url
  libs/backend/src/types/games.ts
  libs/backend/src/websocket/waiting-room/join-game.ts
  libs/backend/src/websocket/waiting-room/remove-empty-games.ts
  libs/backend/src/websocket/waiting-room/remove-player-from-games.ts
  libs/backend/src/websocket/waiting-room/update-players.ts
  libs/frontend/src/routes/(authenticated)/multiplayer/+page.svelte
Labels: feature

#38 height of editor too tall
  libs/frontend/src/lib/features/game/components/codemirror.svelte
Labels: enhancement

#39 fix: id at the end of some schema fields
  libs/backend/src/models/puzzle/puzzle.ts
  libs/backend/src/models/submission/submission.ts
  libs/backend/src/routes/puzzle/[id]/index.ts
  libs/backend/src/routes/submission/game/index.ts
  libs/backend/src/routes/submission/index.ts
  libs/backend/src/utils/functions/convert-raw-data-to-string.ts
  libs/backend/src/utils/functions/generate-random-object-id-string.ts
  libs/backend/src/utils/functions/parse-raw-data-message.ts
  libs/backend/src/websocket/game/update-players-on-game-state.ts
  libs/backend/src/websocket/waiting-room/host-game.ts
  libs/frontend/src/lib/components/ui/countdown-timer/countdown-timer.svelte
  libs/frontend/src/lib/features/authentication/utils/get-cookie.ts
  libs/frontend/src/lib/features/game/standings/components/standings-table.svelte
  libs/frontend/src/lib/features/puzzles/components/edit-puzzle-form.svelte
  libs/frontend/src/lib/features/puzzles/components/puzzle-meta-info.svelte
  libs/frontend/src/lib/utils/format-to-two-digits.ts
  libs/frontend/src/lib/utils/get-last-segment.ts
  libs/frontend/src/lib/utils/get-user-id-from-user.ts
  libs/frontend/src/lib/utils/group-activity-by-created-at-date.ts
  libs/frontend/src/routes/(authenticated)/multiplayer/+page.svelte
  libs/frontend/src/routes/(authenticated)/multiplayer/[id]/+page.svelte
  libs/frontend/src/routes/(authenticated)/puzzles/[id]/edit/+page.svelte
  libs/frontend/src/routes/logout/+page.server.ts
  libs/frontend/src/routes/profile/[username]/+page.svelte
  libs/frontend/src/routes/puzzles/[id]/+page.svelte
  libs/types/src/core/game/schema/game-entity.schema.ts
  libs/types/src/core/puzzle/schema/puzzle-entity.schema.ts
  libs/types/src/core/submission/schema/submission-entity.schema.ts
  libs/types/src/index.ts
  libs/types/src/utils/functions/getKeys.ts
  libs/types/src/utils/functions/is-creator.ts
Labels: bug, enhancement

#41 feat: set db name in env
  libs/backend/.env.example
  libs/backend/src/app.ts
  libs/backend/src/plugins/config/mongoose.ts
Labels: feature

#50 fix code submitting
  libs/backend/src/routes/submission/game/index.ts
  libs/backend/src/routes/submission/index.ts
  libs/backend/src/websocket/waiting-room/start-game.ts
  libs/frontend/src/lib/features/puzzles/components/play-puzzle.svelte
  libs/frontend/src/routes/(authenticated)/multiplayer/[id]/+page.svelte
  libs/frontend/src/routes/api/submit-code/+server.ts
  libs/frontend/src/routes/puzzles/[id]/+page.svelte
  libs/types/package.json
  libs/types/src/core/activity/schema/activity.schema.ts
  libs/types/src/core/authentication/schema/authenticated-info.schema.ts
  libs/types/src/core/authentication/schema/identifier.schema.ts
  libs/types/src/core/common/schema/object-id.ts
  libs/types/src/core/game/schema/game-dto.schema.ts
  libs/types/src/core/game/schema/game-entity.schema.ts
  libs/types/src/core/moderation/schema/report.schema.ts
  libs/types/src/core/profile/schema/profile-dto.schema.ts
  libs/types/src/core/puzzle/schema/puzzle-dto.schema.ts
  libs/types/src/core/puzzle/schema/puzzle-entity.schema.ts
  libs/types/src/core/submission/config/code-submission-params.ts
  libs/types/src/core/submission/config/game-submission-params.ts
  libs/types/src/core/submission/config/submission-params.ts
  libs/types/src/core/submission/schema/submission-dto.schema.ts
  libs/types/src/core/user/schema/user-dto.schema.ts
  libs/types/src/index.ts
  pnpm-lock.yaml
Labels: enhancement, feature

#53 Improve puzzles page with table
  libs/backend/src/router.ts
  libs/backend/src/routes/puzzle/index.ts
  libs/backend/src/routes/submission/[id]/index.ts
  libs/frontend/src/app.css
  libs/frontend/src/lib/components/ui/alert/index.ts
  libs/frontend/src/lib/components/ui/badge/badge.svelte
  libs/frontend/src/lib/components/ui/badge/index.ts
  libs/frontend/src/lib/config/api.ts
  libs/frontend/src/lib/features/game/components/codemirror.svelte
  libs/frontend/src/lib/features/game/standings/components/standings-table.svelte
  libs/frontend/src/lib/features/puzzles/components/play-puzzle.svelte
  libs/frontend/src/lib/features/puzzles/components/puzzle-difficulty-badge.svelte
  libs/frontend/src/lib/features/puzzles/components/puzzle-result-badge.svelte
  libs/frontend/src/lib/features/puzzles/components/puzzle-visibility-badge.svelte
  libs/frontend/src/lib/features/puzzles/utils/calculate-puzzle-result-color.ts
  libs/frontend/src/routes/api/submission/[id]/+server.ts
  libs/frontend/src/routes/puzzles/+page.svelte
  libs/frontend/tailwind.config.ts
  libs/types/src/core/common/config/backend-urls.ts
  libs/types/src/core/puzzle/enum/puzzle-result-enum.ts
  libs/types/src/core/puzzle/schema/difficulty.schema.ts
Labels: enhancement

#59 Fix standings table caching issue with code
  libs/frontend/src/lib/features/game/standings/components/standings-table.svelte
Labels: bug, enhancement

#62 Fix issues with validator fields going out of bounds
  libs/backend/src/websocket/game/on-message.ts
  libs/frontend/src/lib/features/puzzles/components/play-puzzle.svelte
  libs/frontend/src/routes/(authenticated)/multiplayer/+page.svelte
  libs/frontend/src/routes/(authenticated)/multiplayer/[id]/+page.svelte
Labels: bug

#63 Fix standings table no refresh issue and reconnection issues with websockets
  libs/frontend/package.json
  libs/frontend/src/lib/components/ui/scroll-area/index.ts
  libs/frontend/src/lib/components/ui/scroll-area/scroll-area-scrollbar.svelte
  libs/frontend/src/lib/components/ui/scroll-area/scroll-area.svelte
  libs/frontend/src/lib/features/puzzles/components/edit-puzzle-form.svelte
  libs/frontend/src/lib/features/puzzles/components/play-puzzle.svelte
  pnpm-lock.yaml
Labels: bug

#71 Add sleep for better feedback
  libs/frontend/src/lib/features/puzzles/components/play-puzzle.svelte
  libs/frontend/src/lib/utils/fetch-supported-languages.ts
  libs/frontend/src/routes/(authenticated)/game/.gitkeep
Labels: bug, enhancement

#72 fix: access token expired but not visible in frontend issue
  libs/frontend/src/lib/stores/index.ts
  libs/frontend/src/routes/+layout.server.ts
  libs/frontend/src/routes/+layout.svelte
Labels: bug, enhancement

#87 feat introduce more general language highlighting support
  libs/frontend/package.json
  libs/frontend/src/lib/features/game/components/codemirror.svelte
  libs/frontend/src/lib/features/puzzles/components/edit-puzzle-form.svelte
  libs/frontend/src/lib/features/puzzles/components/language-select.svelte
  libs/frontend/src/lib/features/puzzles/components/play-puzzle.svelte
  libs/types/src/core/game/config/game.ts
  pnpm-lock.yaml
Labels: enhancement, feature

#80 feat: add user preferences
  libs/backend/src/models/game/game.ts
  libs/backend/src/models/preferences/preferences.ts
  libs/backend/src/models/user/user.ts
  libs/backend/src/router.ts
  libs/backend/src/routes/account/preferences/index.ts
  libs/backend/src/routes/execute/index.ts
  libs/backend/src/routes/puzzle/[id]/index.ts
  libs/backend/src/routes/puzzle/index.ts
  libs/backend/src/routes/submission/[id]/index.ts
  libs/backend/src/routes/submission/game/index.ts
  libs/backend/src/routes/submission/index.ts
  libs/backend/src/types/fastify.d.ts
  libs/backend/src/utils/constants/model.ts
  libs/frontend/src/lib/config/api.ts
  libs/frontend/src/lib/config/theme-option.ts
  libs/frontend/src/lib/features/authentication/utils/fetch-with-authentication-cookie.ts
  libs/frontend/src/lib/features/game/standings/components/standings-table.svelte
  libs/frontend/src/lib/stores/index.ts
  libs/frontend/src/lib/stores/preferences.ts
  libs/frontend/src/routes/api/account/preferences/+server.ts
  libs/frontend/src/routes/api/execute-code/+server.ts
  libs/frontend/src/routes/api/submission/[id]/+server.ts
  libs/frontend/src/routes/api/submit-code/+server.ts
  libs/frontend/src/routes/api/submit-game/+server.ts
  libs/frontend/src/routes/api/supported-languages/+server.ts
  libs/frontend/src/routes/api/user/[username]/+server.ts
  libs/types/src/core/common/config/backend-urls.ts
  libs/types/src/core/preferences/enum/theme-option.ts
  libs/types/src/core/preferences/schema/preferences-dto.schema.ts
  libs/types/src/core/preferences/schema/preferences-entity.schema.ts
  libs/types/src/index.ts
Labels: enhancement, feature

#82 Reduce line height in code blocks
  libs/frontend/src/app.css
  libs/frontend/src/lib/components/typography/markdown.svelte
  libs/frontend/src/lib/features/puzzles/components/output-box.svelte
  libs/frontend/src/lib/features/puzzles/components/play-puzzle.svelte
Labels: bug, enhancement

#92 Message container height grows after X messages
  libs/frontend/src/lib/features/chat/components/chat.svelte
  libs/frontend/src/lib/features/puzzles/components/edit-puzzle-form.svelte
Labels: bug

#93 feat add keymapping options
  libs/backend/src/models/preferences/preferences-editor.ts
  libs/backend/src/models/preferences/preferences.ts
  libs/backend/src/websocket/game/on-message.ts
  libs/frontend/package.json
  libs/frontend/src/app.html
  libs/frontend/src/lib/config/local-storage.ts
  libs/frontend/src/lib/features/game/components/codemirror.svelte
  libs/frontend/src/lib/features/puzzles/components/language-select.svelte
  libs/frontend/src/lib/stores/index.ts
  libs/frontend/src/lib/stores/preferences.ts
  libs/frontend/src/routes/(authenticated)/settings/preferences/+page.svelte
  libs/frontend/static/apple-touch-icon-114x114-precomposed.png
  libs/frontend/static/apple-touch-icon-120x120-precomposed.png
  libs/frontend/static/apple-touch-icon-144x144-precomposed.png
  libs/frontend/static/apple-touch-icon-152x152-precomposed.png
  libs/frontend/static/apple-touch-icon-180x180-precomposed.png
  libs/frontend/static/apple-touch-icon-57x57-precomposed.png
  libs/frontend/static/apple-touch-icon-60x60-precomposed.png
  libs/frontend/static/apple-touch-icon-72x72-precomposed.png
  libs/frontend/static/apple-touch-icon-76x76-precomposed.png
  libs/frontend/static/apple-touch-icon-precomposed.png
  libs/types/src/core/preferences/config/editor-config.ts
  libs/types/src/core/preferences/enum/keymap.ts
  libs/types/src/core/preferences/schema/editor.schema.ts
  libs/types/src/core/preferences/schema/preferences-dto.schema.ts
  libs/types/src/core/preferences/schema/preferences-entity.schema.ts
  libs/types/src/index.ts
  pnpm-lock.yaml
Labels: feature

#99 Feat maintenance page
  libs/frontend/src/lib/components/nav/nav.svelte
  libs/frontend/src/lib/features/learn/components/become-a-contributor.svelte
  libs/frontend/src/routes/(unauthenticated-only)/register/+page.svelte
  libs/maintenance/.editorconfig
  libs/maintenance/.gitignore
  libs/maintenance/.prettierrc
  libs/maintenance/.vscode/settings.json
  libs/maintenance/maintenance.html
  libs/maintenance/package.json
  libs/maintenance/src/global.d.ts
  libs/maintenance/src/index.ts
  libs/maintenance/src/maintenance.html
  libs/maintenance/test/index.spec.ts
  libs/maintenance/test/tsconfig.json
  libs/maintenance/tsconfig.json
  libs/maintenance/vitest.config.mts
  libs/maintenance/worker-configuration.d.ts
  libs/maintenance/wrangler.jsonc
  libs/types/src/general.ts
  libs/types/src/index.ts
  pnpm-lock.yaml
Labels: enhancement, feature

#101 fix: issues related to loading preferences
  libs/frontend/src/lib/stores/index.ts
Labels: bug, enhancement

#102 fix: navigation items don't take full width
  libs/frontend/src/lib/components/nav/user-dropdown.svelte
Labels: bug

#103 fix: keymap description
  libs/frontend/src/routes/(authenticated)/settings/preferences/+page.svelte
Labels: bug, enhancement

#105 Feat `just piston-remove` command
  justfile
  libs/maintenance/src/index.ts
  libs/maintenance/src/maintenance.html
Labels: enhancement, feature

#107 Fix code execution issues
  libs/backend/package.json
  libs/backend/src/app.ts
  libs/backend/src/config/schema.ts
  libs/backend/src/plugins/config/db-connector.ts
  libs/backend/src/routes/execute/index.ts
  libs/backend/src/routes/submission/index.ts
  libs/backend/src/utils/functions/calculate-result.ts
  libs/frontend/src/lib/components/typography/markdown.svelte
  libs/frontend/src/lib/features/puzzles/components/play-puzzle.svelte
  libs/frontend/src/lib/features/puzzles/components/test-progress-bar.svelte
  libs/frontend/src/lib/features/puzzles/components/validator-status.svelte
  libs/types/src/core/common/schema/error-response.schema.ts
  libs/types/src/core/piston/schema/code-execution-response.ts
  libs/types/src/core/piston/schema/execution-response/code-compilation.schema.ts
  libs/types/src/core/piston/schema/execution-response/code-run.schema.ts
  libs/types/src/core/piston/schema/execution-response/execution-success.ts
  libs/types/src/core/piston/schema/puzzle-result-information.schema.ts
  libs/types/src/index.ts
  pnpm-lock.yaml
  storage/default__vector_store.json
  storage/docstore.json
  storage/graph_store.json
  storage/image__vector_store.json
  storage/index_store.json
Labels: bug, enhancement

#108 feat: add language support for prolog, crystal, lua, go and cobol
  libs/frontend/package.json
  libs/frontend/src/lib/features/game/components/codemirror.svelte
  pnpm-lock.yaml
Labels: feature

#109 Fix back button in settings issue
  libs/frontend/src/routes/(authenticated)/settings/+page.svelte
Labels: bug

#110 Standing table score
  libs/backend/src/models/submission/result-info.ts
  libs/backend/src/models/submission/submission.ts
  libs/backend/src/plugins/config/swagger-ui.ts
  libs/backend/src/plugins/config/swagger.ts
  libs/backend/src/plugins/decorators/piston.ts
  libs/backend/src/routes/execute/index.ts
  libs/backend/src/routes/puzzle/languages/index.ts
  libs/backend/src/routes/submission/index.ts
  libs/backend/src/types/fastify.d.ts
  libs/backend/src/utils/functions/calculate-result.ts
  libs/frontend/src/app.css
  libs/frontend/src/lib/features/game/standings/components/standings-table.svelte
  libs/frontend/src/lib/features/puzzles/components/edit-puzzle-form.svelte
  libs/frontend/src/lib/features/puzzles/components/puzzle-result-badge.svelte
  libs/frontend/src/lib/features/puzzles/utils/calculate-puzzle-result-color.ts
  libs/frontend/src/routes/(authenticated)/multiplayer/[id]/+page.svelte
  libs/types/src/core/piston/schema/execution-response/execution-response.ts
  libs/types/src/core/piston/schema/puzzle-result-information.schema.ts
  libs/types/src/core/piston/schema/runtime.ts
  libs/types/src/core/submission/schema/submission-entity.schema.ts
Labels: enhancement, feature

#33 More welcoming landing page
  libs/frontend/src/routes/+page.svelte
Labels: enhancement, feature

#113 Fix puzzle submitting issues
  libs/backend/src/plugins/config/setup-web-sockets.ts
  libs/backend/src/router.ts
  libs/backend/src/routes/puzzle/[id]/index.ts
  libs/backend/src/routes/puzzle/[id]/solution/index.ts
  libs/backend/src/routes/puzzle/index.ts
  libs/backend/src/routes/submission/[id]/index.ts
  libs/backend/src/types/types.d.ts
  libs/backend/src/websocket/game/play-game.ts
  libs/frontend/src/lib/features/puzzles/components/edit-puzzle-form.svelte
  libs/frontend/src/routes/(authenticated)/puzzles/[id]/edit/+page.server.ts
  libs/frontend/src/routes/(authenticated)/puzzles/[id]/edit/+page.svelte
  libs/types/src/core/common/config/backend-urls.ts
  libs/types/src/core/common/schema/object-id.ts
  libs/types/src/core/puzzle/schema/puzzle-entity.schema.ts
  libs/types/src/utils/functions/get-user-id-from-user.ts
Labels: bug

#114 fix: language select
  libs/frontend/src/lib/features/puzzles/components/edit-puzzle-form.svelte
  libs/frontend/src/lib/features/puzzles/components/language-select.svelte
  libs/frontend/src/lib/features/puzzles/components/play-puzzle.svelte
  libs/frontend/src/lib/stores/languages.ts
  libs/frontend/src/routes/(authenticated)/settings/preferences/+page.svelte
Labels: bug, enhancement
